drop schema if exists chat cascade;
create schema if not exists chat;

create table chat.users
(
    id       integer generated by default as identity (start with 1) primary key,
    email    varchar(50) unique,
    password varchar(50) unique
);