create schema shop authorization dba;

CREATE TABLE shop.PRODUCTS(
                                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            name VARCHAR(16) NOT NULL,
                                            price INTEGER NOT NULL
)
