create schema shop authorization dba;

CREATE TABLE shop.PRODUCTS
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(16) NOT NULL,
    price INTEGER     NOT NULL
);

create table users
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login          VARCHAR(16) NOT NULL,
    password       VARCHAR(16) NOT NULL,
    authentication boolean     not null
)
